<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class OptionValue extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(OptionCategory::class, 'option_category_id');
    }

    public function optionSecondary()
    {
        return $this->hasMany(OptionSecondary::class, 'secondary_option_value_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleted(function ($option) {
            $option->optionSecondary()->delete();
        });
    }

}
