image: ammardev0/php:8.0

pipelines:
  pull-requests:
    '**':
      - step:
          name: Prepare
          script:
            - composer install
          artifacts:
            - vendor/**
          caches:
            - composer

  branches:
    # master:
    #   - step:
    #       name: Prepare
    #       script:
    #         - composer install
    #       artifacts:
    #         - vendor/**
    #       caches:
    #         - composer
    #   - step:
    #       name: Deploy
    #       deployment: production
    #       script:
    #           - ./vendor/bin/envoy run deploy

    develop:
      - step:
          name: Prepare
          script:
            - composer global require "laravel/envoy"
          artifacts:
            - vendor/**
          caches:
            - composer
      - step:
          name: Deploy
          deployment: staging
          script:
            - php ~/.composer/vendor/bin/envoy run deploy
              
definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'minpizza'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'staging'
        MYSQL_PASSWORD: 'YgQR$Zg5tbWTd9#b'